baseURL = "https://www.richardlyon.net/"
languageCode = "en-gb"
title = "richard lyon"

[permalinks]
  essays = "/:year/:month/:title/"
  photos = "/:year/:month/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"