baseURL = "https://www.richardlyon.net/"
languageCode = "en-gb"
title = "richard lyon"
sectionPagesMenu = "main"

[permalinks]
  essays = "/:year/:month/:title/"
  photos = "/:year/:month/:title/"

[taxonomies]
  topic = "topics"
  tag = "tags"